image: 'rust:latest'

stages:
  - test
  - doc
  - publish

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --features=full

pages:
  stage: doc
  script:
    - cargo doc --features=full --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=milston">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

publish:
  stage: publish
  script:
    - cargo publish
  only:
    - master
    - tags      

cache:
  paths:
    - cargo/
    - target/